#!/bin/bash
which chromium-browser || (echo "This application requires chromium-browser to be installed" && exit 1)

pushd $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd) >/dev/null

wget -N https://nodejs.org/dist/v22.16.0/node-v22.16.0-linux-x64.tar.xz

if [ node-v22.16.0-linux-x64.tar.xz -nt node-v22.16.0-linux-x64 ]; then
  rm -rf node-v22.16.0-linux-x64
  tar xJfm node-v22.16.0-linux-x64.tar.xz
  ln -sf node-v22.16.0-linux-x64 node
fi

if ! [ -d node_modules ]; then
  node/bin/npm install
fi

popd >/dev/null
